# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	# allow hostname resolution
	config.vm.provision :hosts do |prov|
		prov.add_host '192.168.33.5', ['puppet.local']
		prov.add_host '192.168.33.6', ['puppetdb.local']
		prov.add_host '192.168.33.7', ['postgres-puppetdb.local']
		prov.add_host '192.168.33.8', ['puppetexplorer.local']
		prov.add_host '192.168.33.9', ['foreman.local']
		prov.add_host '192.168.33.10', ['puppetclient-01.local']
		prov.add_host '192.168.33.11', ['puppetclient-02.local']
		prov.add_host '192.168.33.12', ['puppetclient-03.local']
		prov.add_host '192.168.33.13', ['puppetclient-04.local']
		prov.add_host '192.168.33.14', ['puppetclient-05.local']
	end

  # puppetclient01 node
  config.vm.define "puppetclient01" do |pc01|
		pc01.vm.box = "elastic/oraclelinux-7-x86_64"
		pc01.vm.box_url = "https://atlas.hashicorp.com/elastic/oraclelinux-7-x86_64"
		pc01.vm.hostname = "puppetclient-01.local"
		pc01.vm.network "private_network", ip: "192.168.33.10"
		pc01.vm.provision :shell, :path => "../../installation/prepare-install-rhel.sh"
		pc01.vm.provision :shell, :path => "../../installation/install-puppet4-rhel.sh"
		pc01.vm.provider "virtualbox" do |v|
			v.memory = 1024 
			v.cpus = 1
		end
	end

  # puppetclient02 node
  config.vm.define "puppetclient02" do |pc02|
		pc02.vm.box = "elastic/oraclelinux-7-x86_64"
		pc02.vm.box_url = "https://atlas.hashicorp.com/elastic/oraclelinux-7-x86_64"
		pc02.vm.hostname = "puppetclient-02.local"
		pc02.vm.network "private_network", ip: "192.168.33.11"
		pc02.vm.provision :shell, :path => "../../installation/prepare-install-rhel.sh"
		pc02.vm.provision :shell, :path => "../../installation/install-puppet4-rhel.sh"
		pc02.vm.provider "virtualbox" do |v|
			v.memory = 1024 
			v.cpus = 1
		end
	end
  
	# puppetclient03 node
  config.vm.define "puppetclient03" do |pc03|
		pc03.vm.box = "elastic/oraclelinux-7-x86_64"
		pc03.vm.box_url = "https://atlas.hashicorp.com/elastic/oraclelinux-7-x86_64"
		pc03.vm.hostname = "puppetclient-03.local"
		pc03.vm.network "private_network", ip: "192.168.33.12"
		pc03.vm.provision :shell, :path => "../../installation/prepare-install-rhel.sh"
		pc03.vm.provision :shell, :path => "../../installation/install-puppet4-rhel.sh"
		pc03.vm.provider "virtualbox" do |v|
			v.memory = 1024 
			v.cpus = 1
		end
	end
  
	# puppetclient04 node
  config.vm.define "puppetclient04" do |pc04|
		pc04.vm.box = "elastic/oraclelinux-7-x86_64"
		pc04.vm.box_url = "https://atlas.hashicorp.com/elastic/oraclelinux-7-x86_64"
		pc04.vm.hostname = "puppetclient-04.local"
		pc04.vm.network "private_network", ip: "192.168.33.13"
		pc04.vm.provision :shell, :path => "../../installation/prepare-install-rhel.sh"
		pc04.vm.provision :shell, :path => "../../installation/install-puppet4-rhel.sh"
		pc04.vm.provider "virtualbox" do |v|
			v.memory = 1024 
			v.cpus = 1
		end
	end
  
	# puppetclient05 node
  config.vm.define "puppetclient05" do |pc05|
		pc05.vm.box = "elastic/oraclelinux-7-x86_64"
		pc05.vm.box_url = "https://atlas.hashicorp.com/elastic/oraclelinux-7-x86_64"
		pc05.vm.hostname = "puppetclient-05.local"
		pc05.vm.network "private_network", ip: "192.168.33.15"
		pc05.vm.provision :shell, :path => "../../installation/prepare-install-rhel.sh"
		pc05.vm.provision :shell, :path => "../../installation/install-puppet4-rhel.sh"
		pc05.vm.provider "virtualbox" do |v|
			v.memory = 1024 
			v.cpus = 1
		end
	end

end
